run:
  concurrency: 4
  timeout: 5m
  tests: true

linters-settings:
  #errcheck:
    #exclude: /path/to/file.txt
  lll:
    line-length: 300
  funlen:
    statements: 45
linters:
  enable-all: true
  disable:
    - depguard
    - varnamelen
    - tagliatelle
    - exhaustruct
    - wrapcheck
    - wsl
    - nlreturn
    - godot
