version: "2"
run:
  concurrency: 4
  tests: true
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - nlreturn
    - tagliatelle
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
    - gosmopolitan
    - ireturn
    - noinlineerr
    - godot
  settings:
    funlen:
      statements: 45
    lll:
      line-length: 300
    revive:
      rules:
        - name: var-naming
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - var-naming
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
